### ISSUE TITLE
Version Update 2.3.6

### ISSUE THREAD

**Issue by marcpopp** [puppe/btsync-qpkg#7]
Hello,

I really like and use this app on my QNAP TS-412. When can we have the update to Version 2.3.6 which should support selective sync?

Thanks
Marc

**Comment by puppe** [comment]
I have updated the version to 2.3.6. Since I don't use btsync on my QNAP NAS anymore, I have not tested it. But the URLs are still valid, and the build process should work just as before. Have fun! :-)
